local Factory = require("vibing.infrastructure.adapter.factory")
local Modes = require("vibing.core.constants.modes")

describe("adapter factory", function()
  describe("adapter_name", function()
    it("maps each agent type to its adapter name", function()
      assert.are.equal("claude_cli", Factory.adapter_name("claude"))
      assert.are.equal("codex_cli", Factory.adapter_name("codex"))
      assert.are.equal("copilot_cli", Factory.adapter_name("copilot"))
    end)

    it("falls back to claude_cli for unknown or nil agent types", function()
      assert.are.equal("claude_cli", Factory.adapter_name("nonexistent"))
      assert.are.equal("claude_cli", Factory.adapter_name(nil))
    end)
  end)

  describe("create", function()
    it("creates the adapter matching the agent type", function()
      assert.are.equal("claude_cli", Factory.create("claude", {}).name)
      assert.are.equal("codex_cli", Factory.create("codex", {}).name)
      assert.are.equal("copilot_cli", Factory.create("copilot", {}).name)
    end)

    it("falls back to the claude adapter for unknown agent types", function()
      assert.are.equal("claude_cli", Factory.create("nonexistent", {}).name)
      assert.are.equal("claude_cli", Factory.create(nil, {}).name)
    end)
  end)

  describe("VALID_AGENTS", function()
    it("accepts copilot as a valid agent", function()
      assert.is_true(Modes.is_valid_agent("copilot"))
      assert.is_true(Modes.is_valid_agent("claude"))
      assert.is_true(Modes.is_valid_agent("codex"))
      assert.is_false(Modes.is_valid_agent("nonexistent"))
    end)
  end)
end)
