/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 21
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 18
#define ALIAS_COUNT 0
#define TOKEN_COUNT 10
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_message_header = 1,
  sym_tool_header = 2,
  sym_tool_header_open = 3,
  sym_tool_argument_line = 4,
  sym_tool_argument_end = 5,
  sym_tool_result = 6,
  sym_tool_result_continuation = 7,
  aux_sym_markdown_line_token1 = 8,
  aux_sym_markdown_line_token2 = 9,
  sym_document = 10,
  sym_tool_block = 11,
  sym_markdown_chunk = 12,
  sym_markdown_line = 13,
  aux_sym_document_repeat1 = 14,
  aux_sym_tool_block_repeat1 = 15,
  aux_sym_tool_block_repeat2 = 16,
  aux_sym_markdown_chunk_repeat1 = 17,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_message_header] = "message_header",
  [sym_tool_header] = "tool_header",
  [sym_tool_header_open] = "tool_header_open",
  [sym_tool_argument_line] = "tool_argument_line",
  [sym_tool_argument_end] = "tool_argument_end",
  [sym_tool_result] = "tool_result",
  [sym_tool_result_continuation] = "tool_result_continuation",
  [aux_sym_markdown_line_token1] = "markdown_line_token1",
  [aux_sym_markdown_line_token2] = "markdown_line_token2",
  [sym_document] = "document",
  [sym_tool_block] = "tool_block",
  [sym_markdown_chunk] = "markdown_chunk",
  [sym_markdown_line] = "markdown_line",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_tool_block_repeat1] = "tool_block_repeat1",
  [aux_sym_tool_block_repeat2] = "tool_block_repeat2",
  [aux_sym_markdown_chunk_repeat1] = "markdown_chunk_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_message_header] = sym_message_header,
  [sym_tool_header] = sym_tool_header,
  [sym_tool_header_open] = sym_tool_header_open,
  [sym_tool_argument_line] = sym_tool_argument_line,
  [sym_tool_argument_end] = sym_tool_argument_end,
  [sym_tool_result] = sym_tool_result,
  [sym_tool_result_continuation] = sym_tool_result_continuation,
  [aux_sym_markdown_line_token1] = aux_sym_markdown_line_token1,
  [aux_sym_markdown_line_token2] = aux_sym_markdown_line_token2,
  [sym_document] = sym_document,
  [sym_tool_block] = sym_tool_block,
  [sym_markdown_chunk] = sym_markdown_chunk,
  [sym_markdown_line] = sym_markdown_line,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_tool_block_repeat1] = aux_sym_tool_block_repeat1,
  [aux_sym_tool_block_repeat2] = aux_sym_tool_block_repeat2,
  [aux_sym_markdown_chunk_repeat1] = aux_sym_markdown_chunk_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_message_header] = {
    .visible = true,
    .named = true,
  },
  [sym_tool_header] = {
    .visible = true,
    .named = true,
  },
  [sym_tool_header_open] = {
    .visible = true,
    .named = true,
  },
  [sym_tool_argument_line] = {
    .visible = true,
    .named = true,
  },
  [sym_tool_argument_end] = {
    .visible = true,
    .named = true,
  },
  [sym_tool_result] = {
    .visible = true,
    .named = true,
  },
  [sym_tool_result_continuation] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_markdown_line_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_markdown_line_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_tool_block] = {
    .visible = true,
    .named = true,
  },
  [sym_markdown_chunk] = {
    .visible = true,
    .named = true,
  },
  [sym_markdown_line] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tool_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tool_block_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_markdown_chunk_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(14);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(24);
      if (lookahead == '#') ADVANCE(40);
      if ((!eof && lookahead <= 0x7f)) ADVANCE(106);
      if (lookahead > 0x7f) ADVANCE(23);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(22);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(20);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(17);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(21);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(16);
      END_STATE();
    case 6:
      if (lookahead == '\n') ADVANCE(15);
      END_STATE();
    case 7:
      if (lookahead == '\n') ADVANCE(18);
      END_STATE();
    case 8:
      if (lookahead == '\n') ADVANCE(18);
      if (lookahead == '\r') ADVANCE(7);
      if (lookahead == ')') ADVANCE(10);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == '\n') ADVANCE(19);
      END_STATE();
    case 10:
      if (lookahead == '\n') ADVANCE(19);
      if (lookahead == '\r') ADVANCE(9);
      if (lookahead == ')') ADVANCE(10);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 11:
      if (eof) ADVANCE(14);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(31);
      if (lookahead == '#') ADVANCE(40);
      if ((!eof && lookahead <= 0x7f)) ADVANCE(106);
      if (lookahead > 0x7f) ADVANCE(23);
      END_STATE();
    case 12:
      if (eof) ADVANCE(14);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(38);
      if (lookahead == '#') ADVANCE(40);
      if ((!eof && lookahead <= 0x7f)) ADVANCE(106);
      if (lookahead > 0x7f) ADVANCE(23);
      END_STATE();
    case 13:
      if (eof) ADVANCE(14);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '#') ADVANCE(40);
      if ((!eof && lookahead <= 0x7f)) ADVANCE(106);
      if (lookahead > 0x7f) ADVANCE(23);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_message_header);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_tool_header);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_tool_header_open);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_tool_argument_line);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_tool_argument_end);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_tool_result);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_tool_result_continuation);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_markdown_line_token1);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\t') ADVANCE(106);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(105);
      if (lookahead != 0) ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(32);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(49);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(27);
      if (lookahead == '-') ADVANCE(28);
      if (lookahead != 0) ADVANCE(29);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(27);
      if (lookahead == '-') ADVANCE(26);
      if (lookahead != 0) ADVANCE(29);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(27);
      if (lookahead == '>') ADVANCE(112);
      if (lookahead != 0) ADVANCE(29);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(27);
      if (lookahead != 0) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(50);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(85);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(35);
      if (lookahead == 0x23bf) ADVANCE(107);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(35);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(109);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(34);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(29);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(96);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(33);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '!') ADVANCE(42);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '#') ADVANCE(25);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '(') ADVANCE(108);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '-') ADVANCE(43);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '-') ADVANCE(36);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '-') ADVANCE(95);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '-') ADVANCE(103);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ':') ADVANCE(100);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ':') ADVANCE(104);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '<') ADVANCE(39);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      ADVANCE_MAP(
        '\n', 22,
        '\r', 1,
        'A', 73,
        'N', 64,
        'R', 54,
        'U', 71,
        'S', 90,
        's', 90,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(99);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'A') ADVANCE(78);
      if (lookahead == 'U') ADVANCE(75);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'a') ADVANCE(62);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'a') ADVANCE(63);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'c') ADVANCE(57);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'e') ADVANCE(66);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'e') ADVANCE(69);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'e') ADVANCE(68);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'e') ADVANCE(111);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'e') ADVANCE(74);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'i') ADVANCE(53);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'i') ADVANCE(72);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'i') ADVANCE(76);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'n') ADVANCE(82);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'n') ADVANCE(81);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'o') ADVANCE(80);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'o') ADVANCE(67);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'p') ADVANCE(65);
      if (lookahead == 'q') ADVANCE(84);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'r') ADVANCE(82);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'r') ADVANCE(113);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'r') ADVANCE(111);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 's') ADVANCE(60);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 's') ADVANCE(55);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 's') ADVANCE(79);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 's') ADVANCE(70);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 's') ADVANCE(82);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 's') ADVANCE(56);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 's') ADVANCE(83);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 's') ADVANCE(61);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 's') ADVANCE(77);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 't') ADVANCE(51);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 't') ADVANCE(59);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 't') ADVANCE(113);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 't') ADVANCE(111);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 't') ADVANCE(52);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'u') ADVANCE(58);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 0x23bf) ADVANCE(107);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(89);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(86);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(87);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(91);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(88);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(111);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(92);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(97);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(93);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(94);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(98);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(44);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(101);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(102);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(20);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead != 0) ADVANCE(107);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(17);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == ')') ADVANCE(110);
      if (lookahead != 0) ADVANCE(108);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(21);
      if (lookahead == '\r') ADVANCE(4);
      if (lookahead != 0) ADVANCE(109);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(5);
      if (lookahead == ')') ADVANCE(110);
      if (lookahead != 0) ADVANCE(108);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(15);
      if (lookahead == '\r') ADVANCE(6);
      if (lookahead == ' ') ADVANCE(48);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(15);
      if (lookahead == '\r') ADVANCE(6);
      if (lookahead == ' ') ADVANCE(27);
      if (lookahead != 0) ADVANCE(29);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(15);
      if (lookahead == '\r') ADVANCE(6);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 13},
  [2] = {.lex_state = 13},
  [3] = {.lex_state = 13},
  [4] = {.lex_state = 13},
  [5] = {.lex_state = 12},
  [6] = {.lex_state = 12},
  [7] = {.lex_state = 13},
  [8] = {.lex_state = 12},
  [9] = {.lex_state = 12},
  [10] = {.lex_state = 12},
  [11] = {.lex_state = 12},
  [12] = {.lex_state = 12},
  [13] = {.lex_state = 11},
  [14] = {.lex_state = 11},
  [15] = {.lex_state = 11},
  [16] = {.lex_state = 13},
  [17] = {.lex_state = 8},
  [18] = {.lex_state = 8},
  [19] = {.lex_state = 8},
  [20] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_message_header] = ACTIONS(1),
    [sym_tool_header] = ACTIONS(1),
    [sym_tool_header_open] = ACTIONS(1),
    [sym_tool_result] = ACTIONS(1),
    [sym_tool_result_continuation] = ACTIONS(1),
    [aux_sym_markdown_line_token1] = ACTIONS(1),
    [aux_sym_markdown_line_token2] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(20),
    [sym_tool_block] = STATE(2),
    [sym_markdown_chunk] = STATE(2),
    [sym_markdown_line] = STATE(4),
    [aux_sym_document_repeat1] = STATE(2),
    [aux_sym_markdown_chunk_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_message_header] = ACTIONS(5),
    [sym_tool_header] = ACTIONS(7),
    [sym_tool_header_open] = ACTIONS(9),
    [aux_sym_markdown_line_token1] = ACTIONS(11),
    [aux_sym_markdown_line_token2] = ACTIONS(11),
  },
  [STATE(2)] = {
    [sym_tool_block] = STATE(3),
    [sym_markdown_chunk] = STATE(3),
    [sym_markdown_line] = STATE(4),
    [aux_sym_document_repeat1] = STATE(3),
    [aux_sym_markdown_chunk_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(13),
    [sym_message_header] = ACTIONS(15),
    [sym_tool_header] = ACTIONS(7),
    [sym_tool_header_open] = ACTIONS(9),
    [aux_sym_markdown_line_token1] = ACTIONS(11),
    [aux_sym_markdown_line_token2] = ACTIONS(11),
  },
  [STATE(3)] = {
    [sym_tool_block] = STATE(3),
    [sym_markdown_chunk] = STATE(3),
    [sym_markdown_line] = STATE(4),
    [aux_sym_document_repeat1] = STATE(3),
    [aux_sym_markdown_chunk_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(17),
    [sym_message_header] = ACTIONS(19),
    [sym_tool_header] = ACTIONS(22),
    [sym_tool_header_open] = ACTIONS(25),
    [aux_sym_markdown_line_token1] = ACTIONS(28),
    [aux_sym_markdown_line_token2] = ACTIONS(28),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(33), 1,
      sym_tool_header_open,
    ACTIONS(11), 2,
      aux_sym_markdown_line_token1,
      aux_sym_markdown_line_token2,
    STATE(7), 2,
      sym_markdown_line,
      aux_sym_markdown_chunk_repeat1,
    ACTIONS(31), 3,
      ts_builtin_sym_end,
      sym_message_header,
      sym_tool_header,
  [17] = 4,
    ACTIONS(39), 1,
      sym_tool_result_continuation,
    STATE(6), 1,
      aux_sym_tool_block_repeat2,
    ACTIONS(35), 3,
      ts_builtin_sym_end,
      sym_message_header,
      sym_tool_header,
    ACTIONS(37), 3,
      sym_tool_header_open,
      aux_sym_markdown_line_token1,
      aux_sym_markdown_line_token2,
  [34] = 4,
    ACTIONS(45), 1,
      sym_tool_result_continuation,
    STATE(10), 1,
      aux_sym_tool_block_repeat2,
    ACTIONS(41), 3,
      ts_builtin_sym_end,
      sym_message_header,
      sym_tool_header,
    ACTIONS(43), 3,
      sym_tool_header_open,
      aux_sym_markdown_line_token1,
      aux_sym_markdown_line_token2,
  [51] = 4,
    ACTIONS(49), 1,
      sym_tool_header_open,
    ACTIONS(51), 2,
      aux_sym_markdown_line_token1,
      aux_sym_markdown_line_token2,
    STATE(7), 2,
      sym_markdown_line,
      aux_sym_markdown_chunk_repeat1,
    ACTIONS(47), 3,
      ts_builtin_sym_end,
      sym_message_header,
      sym_tool_header,
  [68] = 4,
    ACTIONS(45), 1,
      sym_tool_result_continuation,
    STATE(10), 1,
      aux_sym_tool_block_repeat2,
    ACTIONS(54), 3,
      ts_builtin_sym_end,
      sym_message_header,
      sym_tool_header,
    ACTIONS(56), 3,
      sym_tool_header_open,
      aux_sym_markdown_line_token1,
      aux_sym_markdown_line_token2,
  [85] = 4,
    ACTIONS(58), 1,
      sym_tool_result_continuation,
    STATE(8), 1,
      aux_sym_tool_block_repeat2,
    ACTIONS(41), 3,
      ts_builtin_sym_end,
      sym_message_header,
      sym_tool_header,
    ACTIONS(43), 3,
      sym_tool_header_open,
      aux_sym_markdown_line_token1,
      aux_sym_markdown_line_token2,
  [102] = 4,
    ACTIONS(64), 1,
      sym_tool_result_continuation,
    STATE(10), 1,
      aux_sym_tool_block_repeat2,
    ACTIONS(60), 3,
      ts_builtin_sym_end,
      sym_message_header,
      sym_tool_header,
    ACTIONS(62), 3,
      sym_tool_header_open,
      aux_sym_markdown_line_token1,
      aux_sym_markdown_line_token2,
  [119] = 4,
    ACTIONS(67), 1,
      sym_tool_result_continuation,
    STATE(12), 1,
      aux_sym_tool_block_repeat2,
    ACTIONS(54), 3,
      ts_builtin_sym_end,
      sym_message_header,
      sym_tool_header,
    ACTIONS(56), 3,
      sym_tool_header_open,
      aux_sym_markdown_line_token1,
      aux_sym_markdown_line_token2,
  [136] = 4,
    ACTIONS(45), 1,
      sym_tool_result_continuation,
    STATE(10), 1,
      aux_sym_tool_block_repeat2,
    ACTIONS(69), 3,
      ts_builtin_sym_end,
      sym_message_header,
      sym_tool_header,
    ACTIONS(71), 3,
      sym_tool_header_open,
      aux_sym_markdown_line_token1,
      aux_sym_markdown_line_token2,
  [153] = 3,
    ACTIONS(77), 1,
      sym_tool_result,
    ACTIONS(73), 3,
      ts_builtin_sym_end,
      sym_message_header,
      sym_tool_header,
    ACTIONS(75), 3,
      sym_tool_header_open,
      aux_sym_markdown_line_token1,
      aux_sym_markdown_line_token2,
  [167] = 3,
    ACTIONS(79), 1,
      sym_tool_result,
    ACTIONS(35), 3,
      ts_builtin_sym_end,
      sym_message_header,
      sym_tool_header,
    ACTIONS(37), 3,
      sym_tool_header_open,
      aux_sym_markdown_line_token1,
      aux_sym_markdown_line_token2,
  [181] = 3,
    ACTIONS(81), 1,
      sym_tool_result,
    ACTIONS(41), 3,
      ts_builtin_sym_end,
      sym_message_header,
      sym_tool_header,
    ACTIONS(43), 3,
      sym_tool_header_open,
      aux_sym_markdown_line_token1,
      aux_sym_markdown_line_token2,
  [195] = 2,
    ACTIONS(83), 3,
      ts_builtin_sym_end,
      sym_message_header,
      sym_tool_header,
    ACTIONS(85), 3,
      sym_tool_header_open,
      aux_sym_markdown_line_token1,
      aux_sym_markdown_line_token2,
  [206] = 3,
    ACTIONS(87), 1,
      sym_tool_argument_line,
    ACTIONS(89), 1,
      sym_tool_argument_end,
    STATE(19), 1,
      aux_sym_tool_block_repeat1,
  [216] = 3,
    ACTIONS(91), 1,
      sym_tool_argument_line,
    ACTIONS(94), 1,
      sym_tool_argument_end,
    STATE(18), 1,
      aux_sym_tool_block_repeat1,
  [226] = 3,
    ACTIONS(96), 1,
      sym_tool_argument_line,
    ACTIONS(98), 1,
      sym_tool_argument_end,
    STATE(18), 1,
      aux_sym_tool_block_repeat1,
  [236] = 1,
    ACTIONS(100), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 17,
  [SMALL_STATE(6)] = 34,
  [SMALL_STATE(7)] = 51,
  [SMALL_STATE(8)] = 68,
  [SMALL_STATE(9)] = 85,
  [SMALL_STATE(10)] = 102,
  [SMALL_STATE(11)] = 119,
  [SMALL_STATE(12)] = 136,
  [SMALL_STATE(13)] = 153,
  [SMALL_STATE(14)] = 167,
  [SMALL_STATE(15)] = 181,
  [SMALL_STATE(16)] = 195,
  [SMALL_STATE(17)] = 206,
  [SMALL_STATE(18)] = 216,
  [SMALL_STATE(19)] = 226,
  [SMALL_STATE(20)] = 236,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [22] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markdown_chunk, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_markdown_chunk, 1, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tool_block, 2, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tool_block, 2, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tool_block, 3, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tool_block, 3, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_markdown_chunk_repeat1, 2, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_markdown_chunk_repeat1, 2, 0, 0),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_markdown_chunk_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tool_block, 4, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tool_block, 4, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tool_block_repeat2, 2, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_tool_block_repeat2, 2, 0, 0),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tool_block_repeat2, 2, 0, 0), SHIFT_REPEAT(10),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tool_block, 5, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tool_block, 5, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tool_block, 1, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tool_block, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markdown_line, 1, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_markdown_line, 1, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [91] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tool_block_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tool_block_repeat1, 2, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [100] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_vibing(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
