/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 14
#define LARGE_STATE_COUNT 9
#define SYMBOL_COUNT 19
#define ALIAS_COUNT 0
#define TOKEN_COUNT 10
#define EXTERNAL_TOKEN_COUNT 2
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_message_header = 1,
  sym_tool_header = 2,
  sym_tool_result = 3,
  sym_tool_result_continuation = 4,
  sym_thinking_line = 5,
  aux_sym_markdown_line_token1 = 6,
  aux_sym_markdown_line_token2 = 7,
  sym_fenced_markdown_block = 8,
  sym_tool_header_multiline = 9,
  sym_document = 10,
  sym_tool_block = 11,
  sym_thinking_block = 12,
  sym_markdown_chunk = 13,
  sym_markdown_line = 14,
  aux_sym_document_repeat1 = 15,
  aux_sym_tool_block_repeat1 = 16,
  aux_sym_thinking_block_repeat1 = 17,
  aux_sym_markdown_chunk_repeat1 = 18,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_message_header] = "message_header",
  [sym_tool_header] = "tool_header",
  [sym_tool_result] = "tool_result",
  [sym_tool_result_continuation] = "tool_result_continuation",
  [sym_thinking_line] = "thinking_line",
  [aux_sym_markdown_line_token1] = "markdown_line_token1",
  [aux_sym_markdown_line_token2] = "markdown_line_token2",
  [sym_fenced_markdown_block] = "fenced_markdown_block",
  [sym_tool_header_multiline] = "tool_header_multiline",
  [sym_document] = "document",
  [sym_tool_block] = "tool_block",
  [sym_thinking_block] = "thinking_block",
  [sym_markdown_chunk] = "markdown_chunk",
  [sym_markdown_line] = "markdown_line",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_tool_block_repeat1] = "tool_block_repeat1",
  [aux_sym_thinking_block_repeat1] = "thinking_block_repeat1",
  [aux_sym_markdown_chunk_repeat1] = "markdown_chunk_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_message_header] = sym_message_header,
  [sym_tool_header] = sym_tool_header,
  [sym_tool_result] = sym_tool_result,
  [sym_tool_result_continuation] = sym_tool_result_continuation,
  [sym_thinking_line] = sym_thinking_line,
  [aux_sym_markdown_line_token1] = aux_sym_markdown_line_token1,
  [aux_sym_markdown_line_token2] = aux_sym_markdown_line_token2,
  [sym_fenced_markdown_block] = sym_fenced_markdown_block,
  [sym_tool_header_multiline] = sym_tool_header_multiline,
  [sym_document] = sym_document,
  [sym_tool_block] = sym_tool_block,
  [sym_thinking_block] = sym_thinking_block,
  [sym_markdown_chunk] = sym_markdown_chunk,
  [sym_markdown_line] = sym_markdown_line,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_tool_block_repeat1] = aux_sym_tool_block_repeat1,
  [aux_sym_thinking_block_repeat1] = aux_sym_thinking_block_repeat1,
  [aux_sym_markdown_chunk_repeat1] = aux_sym_markdown_chunk_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_message_header] = {
    .visible = true,
    .named = true,
  },
  [sym_tool_header] = {
    .visible = true,
    .named = true,
  },
  [sym_tool_result] = {
    .visible = true,
    .named = true,
  },
  [sym_tool_result_continuation] = {
    .visible = true,
    .named = true,
  },
  [sym_thinking_line] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_markdown_line_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_markdown_line_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_fenced_markdown_block] = {
    .visible = true,
    .named = true,
  },
  [sym_tool_header_multiline] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_tool_block] = {
    .visible = true,
    .named = true,
  },
  [sym_thinking_block] = {
    .visible = true,
    .named = true,
  },
  [sym_markdown_chunk] = {
    .visible = true,
    .named = true,
  },
  [sym_markdown_line] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tool_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_thinking_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_markdown_chunk_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(10);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(19);
      if (lookahead == '#') ADVANCE(35);
      if (lookahead == 0x1f4ad) ADVANCE(18);
      if ((!eof && lookahead <= 0x7f)) ADVANCE(102);
      if (lookahead > 0x7f) ADVANCE(17);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(16);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(15);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(13);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(14);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(12);
      END_STATE();
    case 6:
      if (lookahead == '\n') ADVANCE(11);
      END_STATE();
    case 7:
      if (eof) ADVANCE(10);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(26);
      if (lookahead == '#') ADVANCE(35);
      if (lookahead == 0x1f4ad) ADVANCE(18);
      if ((!eof && lookahead <= 0x7f)) ADVANCE(102);
      if (lookahead > 0x7f) ADVANCE(17);
      END_STATE();
    case 8:
      if (eof) ADVANCE(10);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(33);
      if (lookahead == '#') ADVANCE(35);
      if (lookahead == 0x1f4ad) ADVANCE(18);
      if ((!eof && lookahead <= 0x7f)) ADVANCE(102);
      if (lookahead > 0x7f) ADVANCE(17);
      END_STATE();
    case 9:
      if (eof) ADVANCE(10);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '#') ADVANCE(35);
      if (lookahead == 0x1f4ad) ADVANCE(18);
      if ((!eof && lookahead <= 0x7f)) ADVANCE(102);
      if (lookahead > 0x7f) ADVANCE(17);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_message_header);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_tool_header);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_tool_result);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_tool_result_continuation);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_thinking_line);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_markdown_line_token1);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\t') ADVANCE(102);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(101);
      if (lookahead != 0) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\t') ADVANCE(106);
      if (lookahead == '\n') ADVANCE(15);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == ' ') ADVANCE(105);
      if (lookahead != 0) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(27);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(45);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(22);
      if (lookahead == '-') ADVANCE(23);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(22);
      if (lookahead == '-') ADVANCE(21);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(22);
      if (lookahead == '>') ADVANCE(111);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(22);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(46);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(81);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(29);
      if (lookahead == 0x23bf) ADVANCE(107);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(29);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(30);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(108);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(24);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(92);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(28);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '!') ADVANCE(38);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '#') ADVANCE(20);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '(') ADVANCE(37);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ')') ADVANCE(109);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '-') ADVANCE(39);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '-') ADVANCE(31);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '-') ADVANCE(91);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '-') ADVANCE(99);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ':') ADVANCE(96);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ':') ADVANCE(100);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '<') ADVANCE(34);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      ADVANCE_MAP(
        '\n', 16,
        '\r', 1,
        'A', 69,
        'N', 60,
        'R', 50,
        'U', 67,
        'S', 86,
        's', 86,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(95);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'A') ADVANCE(74);
      if (lookahead == 'U') ADVANCE(71);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'a') ADVANCE(58);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'a') ADVANCE(59);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'c') ADVANCE(53);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'e') ADVANCE(62);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'e') ADVANCE(64);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'e') ADVANCE(65);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'e') ADVANCE(110);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'e') ADVANCE(70);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'i') ADVANCE(49);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'i') ADVANCE(68);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'i') ADVANCE(72);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'n') ADVANCE(77);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'n') ADVANCE(78);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'o') ADVANCE(76);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'o') ADVANCE(63);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'p') ADVANCE(61);
      if (lookahead == 'q') ADVANCE(80);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'r') ADVANCE(77);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'r') ADVANCE(110);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'r') ADVANCE(112);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 's') ADVANCE(56);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 's') ADVANCE(51);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 's') ADVANCE(75);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 's') ADVANCE(66);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 's') ADVANCE(77);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 's') ADVANCE(52);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 's') ADVANCE(79);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 's') ADVANCE(57);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 's') ADVANCE(73);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 't') ADVANCE(47);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 't') ADVANCE(55);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 't') ADVANCE(110);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 't') ADVANCE(112);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 't') ADVANCE(48);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'u') ADVANCE(54);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 0x23bf) ADVANCE(107);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(85);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(82);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(83);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(87);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(84);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(110);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(88);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(93);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(89);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(90);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(94);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(97);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(98);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(15);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == '(') ADVANCE(104);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(103);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(15);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == ')') ADVANCE(104);
      if (lookahead != 0) ADVANCE(104);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(15);
      if (lookahead == '\r') ADVANCE(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(103);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(15);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(13);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead != 0) ADVANCE(107);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(14);
      if (lookahead == '\r') ADVANCE(4);
      if (lookahead != 0) ADVANCE(108);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(12);
      if (lookahead == '\r') ADVANCE(5);
      if (lookahead == ')') ADVANCE(109);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(11);
      if (lookahead == '\r') ADVANCE(6);
      if (lookahead == ' ') ADVANCE(44);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(11);
      if (lookahead == '\r') ADVANCE(6);
      if (lookahead == ' ') ADVANCE(22);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(aux_sym_markdown_line_token2);
      if (lookahead == '\n') ADVANCE(11);
      if (lookahead == '\r') ADVANCE(6);
      if (lookahead != 0) ADVANCE(102);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 9, .external_lex_state = 1},
  [2] = {.lex_state = 9, .external_lex_state = 1},
  [3] = {.lex_state = 9, .external_lex_state = 1},
  [4] = {.lex_state = 9, .external_lex_state = 1},
  [5] = {.lex_state = 8, .external_lex_state = 1},
  [6] = {.lex_state = 9, .external_lex_state = 1},
  [7] = {.lex_state = 8, .external_lex_state = 1},
  [8] = {.lex_state = 8, .external_lex_state = 1},
  [9] = {.lex_state = 7, .external_lex_state = 1},
  [10] = {.lex_state = 9, .external_lex_state = 1},
  [11] = {.lex_state = 9, .external_lex_state = 1},
  [12] = {.lex_state = 9, .external_lex_state = 1},
  [13] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_message_header] = ACTIONS(1),
    [sym_tool_header] = ACTIONS(1),
    [sym_tool_result] = ACTIONS(1),
    [sym_tool_result_continuation] = ACTIONS(1),
    [sym_thinking_line] = ACTIONS(1),
    [aux_sym_markdown_line_token1] = ACTIONS(1),
    [aux_sym_markdown_line_token2] = ACTIONS(1),
    [sym_fenced_markdown_block] = ACTIONS(1),
    [sym_tool_header_multiline] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(13),
    [sym_tool_block] = STATE(2),
    [sym_thinking_block] = STATE(2),
    [sym_markdown_chunk] = STATE(2),
    [sym_markdown_line] = STATE(4),
    [aux_sym_document_repeat1] = STATE(2),
    [aux_sym_thinking_block_repeat1] = STATE(10),
    [aux_sym_markdown_chunk_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_message_header] = ACTIONS(5),
    [sym_tool_header] = ACTIONS(7),
    [sym_thinking_line] = ACTIONS(9),
    [aux_sym_markdown_line_token1] = ACTIONS(11),
    [aux_sym_markdown_line_token2] = ACTIONS(11),
    [sym_fenced_markdown_block] = ACTIONS(5),
    [sym_tool_header_multiline] = ACTIONS(13),
  },
  [STATE(2)] = {
    [sym_tool_block] = STATE(3),
    [sym_thinking_block] = STATE(3),
    [sym_markdown_chunk] = STATE(3),
    [sym_markdown_line] = STATE(4),
    [aux_sym_document_repeat1] = STATE(3),
    [aux_sym_thinking_block_repeat1] = STATE(10),
    [aux_sym_markdown_chunk_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(15),
    [sym_message_header] = ACTIONS(17),
    [sym_tool_header] = ACTIONS(7),
    [sym_thinking_line] = ACTIONS(9),
    [aux_sym_markdown_line_token1] = ACTIONS(11),
    [aux_sym_markdown_line_token2] = ACTIONS(11),
    [sym_fenced_markdown_block] = ACTIONS(17),
    [sym_tool_header_multiline] = ACTIONS(13),
  },
  [STATE(3)] = {
    [sym_tool_block] = STATE(3),
    [sym_thinking_block] = STATE(3),
    [sym_markdown_chunk] = STATE(3),
    [sym_markdown_line] = STATE(4),
    [aux_sym_document_repeat1] = STATE(3),
    [aux_sym_thinking_block_repeat1] = STATE(10),
    [aux_sym_markdown_chunk_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(19),
    [sym_message_header] = ACTIONS(21),
    [sym_tool_header] = ACTIONS(24),
    [sym_thinking_line] = ACTIONS(27),
    [aux_sym_markdown_line_token1] = ACTIONS(30),
    [aux_sym_markdown_line_token2] = ACTIONS(30),
    [sym_fenced_markdown_block] = ACTIONS(21),
    [sym_tool_header_multiline] = ACTIONS(33),
  },
  [STATE(4)] = {
    [sym_markdown_line] = STATE(6),
    [aux_sym_markdown_chunk_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(36),
    [sym_message_header] = ACTIONS(36),
    [sym_tool_header] = ACTIONS(38),
    [sym_thinking_line] = ACTIONS(36),
    [aux_sym_markdown_line_token1] = ACTIONS(11),
    [aux_sym_markdown_line_token2] = ACTIONS(11),
    [sym_fenced_markdown_block] = ACTIONS(36),
    [sym_tool_header_multiline] = ACTIONS(36),
  },
  [STATE(5)] = {
    [aux_sym_tool_block_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(40),
    [sym_message_header] = ACTIONS(40),
    [sym_tool_header] = ACTIONS(42),
    [sym_tool_result_continuation] = ACTIONS(44),
    [sym_thinking_line] = ACTIONS(40),
    [aux_sym_markdown_line_token1] = ACTIONS(42),
    [aux_sym_markdown_line_token2] = ACTIONS(42),
    [sym_fenced_markdown_block] = ACTIONS(40),
    [sym_tool_header_multiline] = ACTIONS(40),
  },
  [STATE(6)] = {
    [sym_markdown_line] = STATE(6),
    [aux_sym_markdown_chunk_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(46),
    [sym_message_header] = ACTIONS(46),
    [sym_tool_header] = ACTIONS(48),
    [sym_thinking_line] = ACTIONS(46),
    [aux_sym_markdown_line_token1] = ACTIONS(50),
    [aux_sym_markdown_line_token2] = ACTIONS(50),
    [sym_fenced_markdown_block] = ACTIONS(46),
    [sym_tool_header_multiline] = ACTIONS(46),
  },
  [STATE(7)] = {
    [aux_sym_tool_block_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(53),
    [sym_message_header] = ACTIONS(53),
    [sym_tool_header] = ACTIONS(55),
    [sym_tool_result_continuation] = ACTIONS(57),
    [sym_thinking_line] = ACTIONS(53),
    [aux_sym_markdown_line_token1] = ACTIONS(55),
    [aux_sym_markdown_line_token2] = ACTIONS(55),
    [sym_fenced_markdown_block] = ACTIONS(53),
    [sym_tool_header_multiline] = ACTIONS(53),
  },
  [STATE(8)] = {
    [aux_sym_tool_block_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(59),
    [sym_message_header] = ACTIONS(59),
    [sym_tool_header] = ACTIONS(61),
    [sym_tool_result_continuation] = ACTIONS(63),
    [sym_thinking_line] = ACTIONS(59),
    [aux_sym_markdown_line_token1] = ACTIONS(61),
    [aux_sym_markdown_line_token2] = ACTIONS(61),
    [sym_fenced_markdown_block] = ACTIONS(59),
    [sym_tool_header_multiline] = ACTIONS(59),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(70), 1,
      sym_tool_result,
    ACTIONS(68), 3,
      sym_tool_header,
      aux_sym_markdown_line_token1,
      aux_sym_markdown_line_token2,
    ACTIONS(66), 5,
      sym_fenced_markdown_block,
      sym_tool_header_multiline,
      ts_builtin_sym_end,
      sym_message_header,
      sym_thinking_line,
  [16] = 4,
    ACTIONS(76), 1,
      sym_thinking_line,
    STATE(11), 1,
      aux_sym_thinking_block_repeat1,
    ACTIONS(74), 3,
      sym_tool_header,
      aux_sym_markdown_line_token1,
      aux_sym_markdown_line_token2,
    ACTIONS(72), 4,
      sym_fenced_markdown_block,
      sym_tool_header_multiline,
      ts_builtin_sym_end,
      sym_message_header,
  [34] = 4,
    ACTIONS(82), 1,
      sym_thinking_line,
    STATE(11), 1,
      aux_sym_thinking_block_repeat1,
    ACTIONS(80), 3,
      sym_tool_header,
      aux_sym_markdown_line_token1,
      aux_sym_markdown_line_token2,
    ACTIONS(78), 4,
      sym_fenced_markdown_block,
      sym_tool_header_multiline,
      ts_builtin_sym_end,
      sym_message_header,
  [52] = 2,
    ACTIONS(87), 3,
      sym_tool_header,
      aux_sym_markdown_line_token1,
      aux_sym_markdown_line_token2,
    ACTIONS(85), 5,
      sym_fenced_markdown_block,
      sym_tool_header_multiline,
      ts_builtin_sym_end,
      sym_message_header,
      sym_thinking_line,
  [65] = 1,
    ACTIONS(89), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(9)] = 0,
  [SMALL_STATE(10)] = 16,
  [SMALL_STATE(11)] = 34,
  [SMALL_STATE(12)] = 52,
  [SMALL_STATE(13)] = 65,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [24] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [30] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markdown_chunk, 1, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_markdown_chunk, 1, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tool_block, 2, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tool_block, 2, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_markdown_chunk_repeat1, 2, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_markdown_chunk_repeat1, 2, 0, 0),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_markdown_chunk_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tool_block, 3, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tool_block, 3, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tool_block_repeat1, 2, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_tool_block_repeat1, 2, 0, 0),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tool_block_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tool_block, 1, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tool_block, 1, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_thinking_block, 1, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_thinking_block, 1, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_thinking_block_repeat1, 2, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_thinking_block_repeat1, 2, 0, 0),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_thinking_block_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markdown_line, 1, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_markdown_line, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_fenced_markdown_block = 0,
  ts_external_token_tool_header_multiline = 1,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_fenced_markdown_block] = sym_fenced_markdown_block,
  [ts_external_token_tool_header_multiline] = sym_tool_header_multiline,
};

static const bool ts_external_scanner_states[2][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_fenced_markdown_block] = true,
    [ts_external_token_tool_header_multiline] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_vibing_external_scanner_create(void);
void tree_sitter_vibing_external_scanner_destroy(void *);
bool tree_sitter_vibing_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_vibing_external_scanner_serialize(void *, char *);
void tree_sitter_vibing_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_vibing(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_vibing_external_scanner_create,
      tree_sitter_vibing_external_scanner_destroy,
      tree_sitter_vibing_external_scanner_scan,
      tree_sitter_vibing_external_scanner_serialize,
      tree_sitter_vibing_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
