local permissions = require("vibing.core.utils.project_codex_permissions")

describe("project_codex_permissions", function()
  local root
  local original_getcwd

  before_each(function()
    root = vim.fn.tempname()
    vim.fn.mkdir(root, "p")
    original_getcwd = vim.fn.getcwd
  end)

  after_each(function()
    vim.fn.getcwd = original_getcwd
    vim.fn.delete(root, "rf")
  end)

  it("creates the default profile in a new .vibing directory", function()
    local path, created = permissions.ensure(root)

    assert.is_true(created)
    assert.equals(root .. "/.vibing/codex-permissions.toml", path)
    assert.same({
      "# Generated by vibing.nvim. Edit this file to customize Codex's project sandbox.",
      'default_permissions = "vibing-project"',
      "",
      "[permissions.vibing-project]",
      'description = "Workspace editing with Git metadata access"',
      'extends = ":workspace"',
      "",
      '[permissions.vibing-project.filesystem.":workspace_roots"]',
      '".git" = "write"',
    }, vim.fn.readfile(path))
    assert.same({
      "-c",
      'default_permissions="vibing-project"',
      "-c",
      'permissions={ vibing-project = { description = "Workspace editing with Git metadata access", extends = ":workspace", filesystem = { ":workspace_roots" = { ".git" = "write" } } } }',
    }, require("vibing.infrastructure.adapter.modules.codex_permission_profile").args(root, {
      permissions = { codex_profile_file = ".vibing/codex-permissions.toml" },
    }))
  end)

  it("backfills an existing .vibing directory when the profile is missing", function()
    vim.fn.mkdir(root .. "/.vibing", "p")

    local path, created = permissions.ensure_existing(root)

    assert.is_true(created)
    assert.equals(1, vim.fn.filereadable(path))
  end)

  it("does not create project state while backfilling a directory with no .vibing", function()
    local path, created = permissions.ensure_existing(root)

    assert.is_nil(path)
    assert.is_false(created)
    assert.equals(0, vim.fn.isdirectory(root .. "/.vibing"))
  end)

  it("is part of the project chat-directory bootstrap", function()
    vim.fn.getcwd = function()
      return root
    end

    local save_dir = require("vibing.presentation.chat.modules.file_manager").get_save_directory({
      save_location_type = "project",
    })

    assert.equals(root .. "/.vibing/chat/", save_dir)
    assert.equals(1, vim.fn.filereadable(permissions.path(root)))
  end)

  it("never overwrites an existing profile", function()
    vim.fn.mkdir(root .. "/.vibing", "p")
    local path = permissions.path(root)
    vim.fn.writefile({ "# mine", 'default_permissions = ":read-only"' }, path)

    local ensured_path, created = permissions.ensure(root)

    assert.equals(path, ensured_path)
    assert.is_false(created)
    assert.same({ "# mine", 'default_permissions = ":read-only"' }, vim.fn.readfile(path))
  end)
end)
