local Modes = require("vibing.core.constants.modes")

describe("Modes agent-aware model helpers", function()
  it("treats Claude shortcuts as valid Claude models only", function()
    assert.is_true(Modes.is_valid_model("sonnet"))
    assert.is_false(Modes.is_valid_model("grok-4.5"))
    assert.is_false(Modes.is_valid_model("gpt-5.5"))
  end)

  it("allows free-form models for grok and codex agents", function()
    assert.is_true(Modes.is_allowed_model_for_agent("grok-4.5", "grok"))
    assert.is_true(Modes.is_allowed_model_for_agent("grok-composer-2.5-fast", "grok"))
    assert.is_true(Modes.is_allowed_model_for_agent("custom-model-id", "grok"))
    assert.is_true(Modes.is_allowed_model_for_agent("gpt-5.5", "codex"))
    assert.is_false(Modes.is_allowed_model_for_agent("grok-4.5", "claude"))
    assert.is_true(Modes.is_allowed_model_for_agent("sonnet", "claude"))
  end)

  it("defaults grok to grok-4.5 when config still has a Claude shortcut", function()
    assert.equals("grok-4.5", Modes.default_model_for_agent("grok", "sonnet"))
    assert.equals("grok-4.5", Modes.default_model_for_agent("grok", nil))
    assert.equals("my-grok", Modes.default_model_for_agent("grok", "my-grok"))
  end)

  it("defaults claude from config", function()
    assert.equals("opus", Modes.default_model_for_agent("claude", "opus"))
    assert.equals("sonnet", Modes.default_model_for_agent("claude", nil))
  end)
end)
