--- Bootstrap the project-local Codex permission profile.
---
--- Every project `.vibing/` directory gets a conservative writable-workspace profile that also
--- permits Git metadata writes. Creation is exclusive, so an existing file -- including an empty
--- one the user deliberately left there -- is never overwritten by another Neovim instance.
--- @module vibing.core.utils.project_codex_permissions

local Fs = require("vibing.core.utils.fs")

local M = {}

local DEFAULT_CONTENT = table.concat({
  "# Generated by vibing.nvim. Edit this file to customize Codex's project sandbox.",
  'default_permissions = "vibing-project"',
  "",
  "[permissions.vibing-project]",
  'description = "Workspace editing with Git metadata access"',
  'extends = ":workspace"',
  "",
  '[permissions.vibing-project.filesystem.":workspace_roots"]',
  '".git" = "write"',
  "",
}, "\n")

--- @param project_root string
--- @return string path
function M.path(project_root)
  return project_root:gsub("/+$", "") .. "/.vibing/codex-permissions.toml"
end

--- Ensure the default profile exists without replacing any existing file.
--- @param project_root string
--- @return string path
--- @return boolean created
function M.ensure(project_root)
  local path = M.path(project_root)
  Fs.ensure_dir(vim.fn.fnamemodify(path, ":h"))

  local fd, open_error = vim.loop.fs_open(path, "wx", 420) -- 0644
  if not fd then
    if vim.loop.fs_stat(path) then
      return path, false
    end
    error(string.format("could not create %q: %s", path, tostring(open_error)))
  end

  local written, write_error = vim.loop.fs_write(fd, DEFAULT_CONTENT, 0)
  vim.loop.fs_close(fd)
  if written ~= #DEFAULT_CONTENT then
    -- We exclusively created this file, so removing a partial write cannot discard user data.
    pcall(vim.loop.fs_unlink, path)
    error(string.format("could not initialize %q: %s", path, tostring(write_error)))
  end

  return path, true
end

--- Backfill the profile only when this project already has a `.vibing/` directory.
--- Unlike `ensure()`, this is safe to call during plugin setup without creating project state in
--- every directory where Neovim happens to start.
--- @param project_root string
--- @return string? path
--- @return boolean created
function M.ensure_existing(project_root)
  local vibing_dir = project_root:gsub("/+$", "") .. "/.vibing"
  if vim.fn.isdirectory(vibing_dir) ~= 1 then
    return nil, false
  end
  return M.ensure(project_root)
end

return M
